version: "3.x"
services:
  db:
    image: postgres:14.3-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  django:
    restart: always
    container_name: backend
    build:
      context: ./jsuite
      dockerfile: Dockerfile
    command: bash -c "python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./jsuite:/app/backend/
    ports:
      - "8080:8080"
    env_file:
      - jsuite/.env.dev
    depends_on:
      - db

  react:
    restart: always
    container_name: frontend
    build:
      context: ./jsuite-frontend
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./jsuite-frontend:/app/frontend/
      - frontend_node_modules:/app/frontend/node_modules/
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - django

volumes:
  frontend_node_modules:
