name: Django_docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEBUG: ${{secrets.DEBUG}}
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  DJANGO_ALLOWED_HOSTS: ${{secrets.DJANGO_ALLOWED_HOSTS}}
  SQL_ENGINE: ${{secrets.SQL_ENGINE}}
  SQL_DATABASE: ${{secrets.SQL_DATABASE}}
  SQL_USER: ${{secrets.SQL_USER}}
  SQL_PASSWORD: ${{secrets.SQL_PASSWORD}}
  SQL_HOST: ${{secrets.SQL_HOST}}
  SQL_PORT: ${{secrets.SQL_PORT}}
  DATABASE: ${{secrets.DATABASE}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker containers
      run: docker-compose up -d
    - name: Run test Django
      run: echo hello
      #run: docker-compose exec -T django python manage.py test
    - name: Run test Node.js 1
      run: |
        docker-compose exec -t react npm ci
        docker-compose exec -t react npm run build --if-present
        docker-compose exec -t react npm test
    env:
      CI: false
        
