name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: jsuite-frontend/package-lock.json

    - name: Run component tests
      run: |
        cd jsuite-frontend
        npm ci
        npm run build --if-present
        npm test

    - name: Run API & e2e tests
      uses: cypress-io/github-action@v4
      with: 
        working-directory: ./jsuite-frontend
        build: npm run build
        start: npm start

        
