name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: jsuite-frontend/package-lock.json

    - name: Run tests
      run: |
        cd jsuite-frontend
        npm ci
        npm run build --if-present
        npm test
        npm start & wait-on http://localhost:3000
        npm run cy:all
      env:
        CI: false
